/** 战场 Venom Lobber 专家怪的波次、环带与技能世界参数。 */
export const BATTLEFIELD_VENOM_LOBBER_CONFIG = Object.freeze({
  populationCapacity: 18,
  openingGraceSeconds: 9,
  firstWaveCount: 2,
  reinforcementCount: 1,
  reinforcementIntervalSeconds: 11,
  spawnInnerRadius: 18,
  spawnOuterRadius: 28,
  recycleRadius: 46,
  hardRecycleRadius: 76,
  seed: 0x76e04b,
  combat: Object.freeze({
    detectionRadius: 42,
    disengageRadius: 56,
    preferredMinimumRange: 8,
    preferredMaximumRange: 19,
    pursuitSpeedMultiplier: 1.65,
    retreatSpeedMultiplier: 1.35,
    castWindupSeconds: 0.92,
    castRecoverySeconds: 0.58,
    minimumCooldownSeconds: 3.1,
    maximumCooldownSeconds: 5.4,
    meleeRange: 2.4,
    meleeDamage: 22,
    meleeWindupSeconds: 0.46,
    meleeRecoverySeconds: 0.62,
    meleeCooldownSeconds: 1.45,
    meleeLungeSpeedMultiplier: 2.15,
    projectileFlightSeconds: 1.38,
    projectileStartElevation: 1.12,
    blastRadius: 2.7,
    blastDamage: 16,
    poolRadius: 2.2,
    poolDurationSeconds: 6.5,
    poolDamagePerSecond: 4.2,
    poolMovementMultiplier: 0.58,
    catalystRadiusMultiplier: 1.55,
    catalystDamageMultiplier: 1.7,
    catalystDurationMultiplier: 1.45,
  }),
});
