import { LOBBY_LAYOUT } from './lobby-layout';

/** 墙后巨型蜘蛛的缩放、运动范围与探头节奏。 */
export const LOBBY_OBSERVATION_SPIDER_CONFIG = Object.freeze({
  initialScale: 0.5,
  minimumScale: 0.5,
  maximumScale: 10,
  floorY: 0.04,
  glassZ: LOBBY_LAYOUT.observationGlassZ,
  watchingClearance: 0.72,
  retreatDepthPerScale: 10,
  roamingHorizontalAmplitude: 4.2,
  roamingDepthAmplitudePerScale: 2.25,
  roamingPathRate: 0.25,
  roamingPositionResponse: 1.45,
  roamingYawResponse: 3.2,
  watchingSideOffset: 2.15,
  watchingInwardYaw: 0.24,
  minimumRoamingDuration: 10,
  roamingDurationRange: 9,
  sidePositioningDuration: 3.6,
  turningDuration: 3.35,
  approachDuration: 5.8,
  watchingDuration: 5.2,
  retreatDuration: 4.8,
  returnTurningDuration: 3.2,
  watchingDriftAmplitude: 0.14,
  watchingDepthDriftPerScale: 0.08,
  localSpawnWidth: 0.52,
  localSpawnHeight: 0.24,
  seed: 0x5a17c3,
});
