import { type FixedTopologyMetrics } from '../../../core/geometry/fixed-topology';
import {
  VANGUARD_ARMOR_PARTS,
  VANGUARD_LIGHT_PARTS,
  VANGUARD_PANEL_PARTS,
  VANGUARD_WEAPON_PARTS,
} from './vanguard-part-layout';

export const VANGUARD_PART_RADIAL_SEGMENTS = 6;
export const VANGUARD_PART_RING_COUNT = 3;
export const VANGUARD_PART_TRIANGLE_COUNT = (VANGUARD_PART_RING_COUNT - 1)
  * VANGUARD_PART_RADIAL_SEGMENTS * 2
  + VANGUARD_PART_RADIAL_SEGMENTS * 2;
export const VANGUARD_PART_VERTEX_COUNT = VANGUARD_PART_TRIANGLE_COUNT * 3;
export const VANGUARD_PART_INDEX_COUNT = VANGUARD_PART_TRIANGLE_COUNT * 3;

export const VANGUARD_EYE_RING_SEGMENTS = 8;
export const VANGUARD_EYE_RING_TRIANGLE_COUNT = VANGUARD_EYE_RING_SEGMENTS * 8;
export const VANGUARD_EYE_RING_VERTEX_COUNT = VANGUARD_EYE_RING_TRIANGLE_COUNT * 3;
export const VANGUARD_EYE_RING_INDEX_COUNT = VANGUARD_EYE_RING_TRIANGLE_COUNT * 3;

export const VANGUARD_ARMOR_VERTEX_COUNT = VANGUARD_ARMOR_PARTS.length
  * VANGUARD_PART_VERTEX_COUNT;
export const VANGUARD_PANEL_VERTEX_COUNT = VANGUARD_PANEL_PARTS.length
  * VANGUARD_PART_VERTEX_COUNT;
export const VANGUARD_WEAPON_VERTEX_COUNT = VANGUARD_WEAPON_PARTS.length
  * VANGUARD_PART_VERTEX_COUNT;

/** 主角装甲与手枪受光层的固定拓扑。 */
export const VANGUARD_OPAQUE_TOPOLOGY = Object.freeze({
  verticesPerEntity: VANGUARD_ARMOR_VERTEX_COUNT
    + VANGUARD_PANEL_VERTEX_COUNT
    + VANGUARD_WEAPON_VERTEX_COUNT,
  indicesPerEntity: (
    VANGUARD_ARMOR_PARTS.length
    + VANGUARD_PANEL_PARTS.length
    + VANGUARD_WEAPON_PARTS.length
  ) * VANGUARD_PART_INDEX_COUNT,
}) satisfies FixedTopologyMetrics;

/** 主角独眼环、镜片、头侧灯和前臂识别灯的固定拓扑。 */
export const VANGUARD_SENSOR_TOPOLOGY = Object.freeze({
  verticesPerEntity: VANGUARD_EYE_RING_VERTEX_COUNT
    + VANGUARD_LIGHT_PARTS.length * VANGUARD_PART_VERTEX_COUNT,
  indicesPerEntity: VANGUARD_EYE_RING_INDEX_COUNT
    + VANGUARD_LIGHT_PARTS.length * VANGUARD_PART_INDEX_COUNT,
}) satisfies FixedTopologyMetrics;
